### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.nlp'

### ISSUE THREAD

**Issue by tdye24** [khushsi/RemRec#1]
Error occurs that `ModuleNotFoundError: No module named 'lib.nlp'` when I run recommendation.py. I wonder if you omit the package `lib.nlp`?

**Comment by khushsi** [comment]
oh  sorry about that - I added it to the github

Somehow the .ignore had .lib folder so it did not push that directory to
github

Let me know if you find any further issues.

Regards,
Khushboo Thaker
Ph.D. Student
PAWS Lab <http://adapt2.sis.pitt.edu/wiki/PAWS>, iRiS Lab
<http://crystal.exp.sis.pitt.edu:8080/iris/>
University of Pittsburgh
https://pitt.edu/~kmt81/
